name: haris
description: "A digital guardian app that enforces daily adhkar, Qur’an, and discipline."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Utils
  path: ^1.9.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  collection: ^1.19.1
  rxdart: ^0.28.0

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0

  # Database
  drift: ^2.28.2
  drift_flutter: ^0.2.7

  # Services
  flutter_overlay_window: ^0.5.0
  flutter_background_service: ^5.1.0

  # UI
  lucide_icons: ^0.257.0
  animated_digit: ^3.3.2

  # Logger
  colored_logger: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Black.ttf
          weight: 900
        - asset: assets/fonts/Lexend/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend/Lexend-Thin.ttf
          weight: 100

